name: Build Files and Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: "yarn"
          cache-dependency-path: "zt_frontend/yarn.lock"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
      
      - name: Build Docs and Frontend
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r docs/requirements.txt
          sphinx-build -b html docs docs/html
          npm install --global yarn
          zero-true-dev build

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-files
          path: |
            zt_backend/dist_app/
            zt_backend/dist_dev/

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Remove Existing Frontend Files
        run: |
          rm -rf zt_backend/dist_dev
          rm -rf zt_backend/dist_app
      
      - name: Download Frontend Files
        uses: actions/download-artifact@v3
        with:
          name: frontend-files
      
      - name: Install
        run: |
          ls -R
          pip install .

      - name: Setup Chrome
        run: sudo apt-get install -y chromium-browser

      - name: Test with pytest
        run: pytest